# Generated by Django 4.2.11 on 2024-04-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salespersons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesperson',
            options={'verbose_name_plural': 'Sales Persons'},
        ),
    ]
