# Generated by Django 4.2.11 on 2024-04-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField()),
                ('genre', models.CharField(max_length=20)),
                ('book_type', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
