# Generated by Django 4.2.11 on 2024-04-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('ebook', 'E-book'), ('audiobook', 'Audio Book'), ('hardcover', 'Hard cover')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('classic', 'Classic'), ('fantasy', 'Fantasy'), ('comedy', 'Comedy'), ('educational', 'Educational'), ('romantic', 'Romantic'), ('horror', 'Horror')], default='cl', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(help_text='in US dollars $'),
        ),
    ]
