# Generated by Django 4.2.11 on 2024-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_book_type_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('ebook', 'E-book'), ('hardcover', 'Hard cover'), ('audiobook', 'Audio Book')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('classic', 'Classic'), ('comedy', 'Comedy'), ('educational', 'Educational'), ('romantic', 'Romantic'), ('fantasy', 'Fantasy'), ('horror', 'Horror')], default='cl', max_length=12),
        ),
    ]
