# Generated by Django 4.2.11 on 2024-04-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_book_type_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('audiobook', 'Audio Book'), ('hardcover', 'Hard cover'), ('ebook', 'E-book')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('classic', 'Classic'), ('romantic', 'Romantic'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('educational', 'Educational')], default='cl', max_length=12),
        ),
    ]
