# Generated by Django 4.2.11 on 2024-04-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_book_type_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hard cover'), ('audiobook', 'Audio Book'), ('ebook', 'E-book')], default='hc', max_length=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('romantic', 'Romantic'), ('horror', 'Horror'), ('classic', 'Classic'), ('educational', 'Educational'), ('fantasy', 'Fantasy')], default='cl', max_length=12),
        ),
    ]
