# Generated by Django 4.2.11 on 2024-04-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='book',
            field=models.CharField(choices=[], default='hc', max_length=40),
        ),
    ]
